---
# This role is used to setup the Raspberry Pi for the PiStream project
# Home streaming with Jellyfin and Moonlight for the Raspberry Pi 5
# Utilizes a minimal Desktop environment with Openbox to start different streaming clients with minimal inputs required
# Felix Nesbigall - 01.02.2025

- name: Update the system
  apt:
    update_cache: yes
    upgrade: dist

- name: Install essentials
  apt:
    pkg:
      - git
      - curl
      - wget
      - unzip
      - btop
      - vlan
      - chromium
      - gnupg
      - pulseaudio
      - flatpak
      - apt-transport-https
      - accountsservice
      - lxterminal
    state: present

- name: Install desktop components
  apt:
    pkg:
      - xorg
      - lightdm
      - openbox
      - rofi
      - libgles2-mesa
      - libgles2-mesa-dev
      - xorg-dev
      - dunst
      - libnotify-bin

- name: Add flatpak repository
  command: flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Check if rebooted file exists
  stat:
    path: /home/user/.flatpak_rebooted
  register: rebooted_file

- name: reboot
  reboot:
    reboot_timeout: 300
  when: not rebooted_file.stat.exists

- name: touch rebooted file
  file:
    path: /home/user/.flatpak_rebooted
    state: touch
  when: not rebooted_file.stat.exists

- name: Install Jellyfin
  flatpak:
    name: com.github.iwalton3.jellyfin-media-player
    state: present

- name: Download repo script
  get_url:
    url: https://dl.cloudsmith.io/public/moonlight-game-streaming/moonlight-qt/setup.deb.sh
    dest: /tmp/setup.deb.sh

- name: Add Moonlight-qt repository
  command: /bin/bash /tmp/setup.deb.sh

- name: Install Moonlight-qt
  apt:
    name: moonlight-qt
    state: present

- name: Create default user without password
  user:
    name: "user"
    shell: /bin/bash
    password: "*"
    createhome: yes

- name: Add the user to the input group
  user:
    name: "user"
    groups: input
    append: yes

- name: copy gtk theme
  copy:
    src: files/themes/Kripton-v40.tar.xz
    dest: /home/user/.themes/Kripton-v40.tar.xz
    owner: user
    group: user
    mode: 0755

- name: extract gtk theme
  unarchive:
    src: /home/user/.themes/Kripton-v40.tar.xz
    dest: /home/user/.themes
    remote_src: yes
    owner: user
    group: user
    mode: 0755

- name: remove the tar file
  file:
    path: /home/user/.themes/Kripton-v40.tar.xz
    state: absent

- name: create gtk settings dir
  file:
    path: /home/user/.config/gtk-3.0
    state: directory

- name: use the gtk theme
  copy:
    content: |
      [Settings]
      gtk-theme-name=Kripton-v40
    dest: /home/user/.config/gtk-3.0/settings.ini
    owner: user
    group: user
    mode: 0644

- name: copy openbox theme
  copy:
    src: files/themes/modernflatdark-master.zip
    dest: /home/user/.themes/modernflatdark-master.zip
    owner: user
    group: user
    mode: 0755

- name: extract openbox theme
  unarchive:
    src: /home/user/.themes/modernflatdark-master.zip
    dest: /home/user/.themes
    remote_src: yes
    owner: user
    group: user
    mode: 0755

- name: remove the zip file
  file:
    path: /home/user/.themes/modernflatdark-master.zip
    state: absent

- name: modify openbox theme - change button color
  replace:
    path: /home/user/.themes/modernflatdark-master/openbox-3/themerc
    regexp: 'window\.active\.button\.(unpressed|pressed|toggled|hover)\.image\.color: #[0-9A-Fa-f]{6}'
    replace: 'window.active.button.\1.image.color: #D3D3D3'

- name: modify openbox theme - change title bar color to gtk theme color
  replace:
    path: /home/user/.themes/modernflatdark-master/openbox-3/themerc
    regexp: 'window\.active\.title\.bg\.color: #[0-9A-Fa-f]{6}'
#    replace: 'window.titlebar.active.bg.color: #15171c'
    replace: 'window.titlebar.active.bg.color: #171a1f'
#    replace: 'window.titlebar.active.bg.color: #131519'

#- name: modify openbox theme - make title bar thinner
#  replace:
#    path: /home/user/.themes/modernflatdark-master/openbox-3/themerc
#    regexp: 'padding\.height: [0-9]+'
#    replace: 'padding.height: 2'

- name: Copy menu script to the user's home directory
  copy:
    src: menu.sh
    dest: /home/user/menu.sh
    owner: user
    group: user
    mode: 0755

- name: autologin user in lightdm
  copy:
    src: files/lightdm.conf
    dest: /etc/lightdm/lightdm.conf
    owner: root
    group: root
    mode: 0644

- name: make openbox autostart directory
  file:
    path: /home/user/.config/openbox
    state: directory

- name: Copy openbox stuff
  copy:
    src: "{{ item }}"
    dest: /home/user/.config/openbox/{{ item }}
    owner: user
    group: user
    mode: 0755
  with_items:
    - autostart

- name: Copy rc.xml from etc/xdg/openbox to user's home directory
  copy:
    src: /etc/xdg/openbox/rc.xml
    dest: /home/user/.config/openbox/rc.xml
    owner: user
    group: user
    mode: 0755
    remote_src: yes

- name: have openbox start windows maximized
  lineinfile:
    path: /home/user/.config/openbox/rc.xml 
    line: |
      <application class="*">
        <maximized>yes</maximized>
      </application>
    insertafter: '<applications>'
    state: present

- name: disable right click conext menu
  lineinfile:
    path: /home/user/.config/openbox/rc.xml
    line: '    <menu>no</menu>'
    insertafter: '<context name="Root">'
    state: present

- name: Change Openbox theme in rc.xml
  ansible.builtin.replace:
    path: /home/user/.config/openbox/rc.xml
    regexp: '(<theme>[\s\S]*?<name>)(.*?)(</name>)'
    replace: '\1modernflatdark-master\3'
  
- name: disable icon and text
  replace:
    path: /home/user/.config/openbox/rc.xml
    regexp: '(<titleLayout>)NLIMC(</titleLayout>)'
    replace: '\1IMC\2'

- name: only one desktop
  replace:
    path: /home/user/.config/openbox/rc.xml
    regexp: '(<number>)4(</number>)'
    replace: '\11\2'

- name: Copy scripts to the user's home directory
  copy:
    src: files/{{ item }}
    dest: /home/user/{{ item }}
    owner: user
    group: user
    mode: 0755
  with_items:
    - menu.sh
    - network-settings.sh
    - show-devices.sh
    - bluetooth-settings.sh

- name: Copy .xsession to the user's home directory
  copy:
    src: files/.xsession
    dest: /home/user/.xsession
    owner: user
    group: user
    mode: 0755

- name: user should own it's own files
  command: chown -R user:user /home/user

- name: set graphical target as default
  command: systemctl set-default graphical.target  

- name: enable lightdm
  systemd:
    name: lightdm
    state: stopped
    enabled: yes

- name: chromium policy directory
  file:
    path: /etc/chromium/policies/managed
    state: directory

- name: configure chromium
  copy:
    content: |
      {
        "SavingBrowserHistoryDisabled": true
        "SearchSuggestEnabled": false
        "AutoFillEnabled": false
      }
    dest: /etc/chromium/policies/managed/custo2m_policy.json
    owner: root
    group: root
    mode: 0644
      
- name: reboot
  reboot:
    reboot_timeout: 300
